### PR TITLE
Full development of Youtube Clone

### PR DESCRIPTION
**Pull request by flpfar**
YouTube Clone project for Basic HTML Structure completed.

This branch contains the entire project and it has been finished. The requirements for the project have been met and also included responsive styling and used Flexbox for positioning and alignment on most of the elements.

Elements added include: 
- Logo in navbar
- Searchbar in navbar
- Supportive buttons in navbar (upload, sing-in, notifications)
- Embedded video
- Video related info (title, owner, views)
- Video related buttons (subscribe, like, dislike, share, etc)
- Recommended videos on right side of the page

Images from YouTube were used, as well as a code snippet for the video player responsiveness.

### CODE REVIEW

**Comment by flpfar** [comment]
The following stickler check seems to be not right, at least it made no sense for us.

Expected selector ".suggested-details span" to come before selector "#subscribe-content span" (no-descending-specificity) [error]

The suggested-details component is in a different section than the subscribe-content.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team       
#### Great Job so far, but there are a few more things required. 
### General
- [x] Pull request should have a meaning short description.
- [ ]  For the Comments in your code: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
### Navigation bar
- [x] You should have at least three embedded images on the rightmost part of the navbar that represents icons and/or an avatar ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/icons_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
##### Yours 


#### Original



### Video
* [x] It has a share button(not a link) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/48945837/))
### Make changes and submit another code review request.
*Happy coding*

**Comment by sebGilR** [comment]
Thank you for the feedback. Could you please specify where the code commented is?
So far what we have in comments is only for code navigation, like specifying what the following code is about, but no code has been commented.

Or, could you confirm if we should just not add any comment at all within our code?

Thanks in advance.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved ✈️ 🎈 

Hi @lBuggie and @flpfar, **congratulations** on a great work done. You did great working on the comment from the previous code reviewer. Your project has met all the minimum requirements. 👍 
You can now merge to master and submit the project completion form 😄 

Good luck with your next project 🙂 
Happy coding 💻 
Daniel Larbi Addo

**Pull request merged**
